<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Era;
use App\Models\Franchise;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $showa = $this->Era('Showa');
        $heisei = $this->Era('Heisei');
        $reiwa = $this->Era('Reiwa');
        $ultraman = $this->Franchise('Ultraman');
        $kamenrider = $this->Franchise('Kamen Rider');
        $supersentai = $this->Franchise('Super Sentai');

        $categories = [
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Kamen Rider',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.1 IchigoNigoRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'V3',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.2 V3RidermanRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'X',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.3 XRider.jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Amazon',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.4 AmazonRider (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Stronger',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.5 StrongerRider (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Skyrider',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.6 SkyRider (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Super-1',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.7 Super1Rider (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'ZX',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.7.Movie 10thKamenRider.jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Black',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.8 BlackRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Black RX',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.9 BlackRXRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'Shin',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.13 ShinRider.jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'ZO',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.14 ZORider.jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $kamenrider,
                'name' => 'J',
                'desc' => null,
                'img' => "Kamen Rider/Era Showa/0.15 JRider.jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Kuuga",
                'desc' => "Kamen Rider Kuuga (仮面ライダークウガ Kamen Raidā Kūga, Masked Rider Kuuga) is a Japanese tokusatsu drama and the 10th installment of the Kamen Rider Series. Debuting as the first entry of the Heisei Era, the series aired from January 30, 2000 to January 21, 2001 on TV Asahi as a joint collaboration between Ishimori Productions and Toei Company.",
                'img' => "Kamen Rider/Era Heisei/1. Kuuga/1.1 kuugaRider (5).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Agito",
                'desc' => "Kamen Rider Agito (仮面ライダーアギト Kamen Raidā Agito, Masked Rider ΑGITΩ), is the eleventh installment in the popular Kamen Rider tokusatsu franchise. The series represented the 30th Anniversary of the Kamen Rider Series. The series was also a joint collaboration between Ishimori Productions and Toei and was shown on TV Asahi from January 28, 2001 to January 27, 2002. The catchphrase for the series is \"Awaken the soul\" (目覚めろ、その魂 Mezamero, sono tamashii).",
                'img' => "Kamen Rider/Era Heisei/2. Agito/1.2 AgitoRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Ryuki",
                'desc' => "Kamen Rider Ryuki (仮面ライダー龍騎 Kamen Raidā Ryūki, Masked Rider Ryuki) is a Japanese tokusatsu television series. It was the twelfth installment in the Kamen Rider Series of tokusatsu shows. It was a joint collaboration between Ishimori Productions and Toei, and it was shown on TV Asahi from February 3, 2002 to January 19, 2003. The catchphrase for the series is \"Those who don't fight won't survive!!\" (戦わなければ、生き残れない!! Tatakawanakereba, ikinokorenai!!). In 2009, Ryuki was adapted into the American television series Kamen Rider Dragon Knight, the first adaptation of a Kamen Rider Series in the United States since Saban's Masked Rider in 1996.",
                'img' => "Kamen Rider/Era Heisei/3. Ryuki/1.3 RyukiRiders (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "555",
                'desc' => "Kamen Rider 555 (仮面ライダー555（ファイズ） Kamen Raidā Faizu, Masked Rider Φ's or Faiz or Phi's) is a Japanese tokusatsu television drama. It is the 13th installment in the Kamen Rider Series. It is a joint collaboration between Ishinomori Productions and Toei, and was broadcast on TV Asahi from January 26, 2003, to January 18, 2004. This series was the first to use TV Asahi's current logo. It aired as a part of TV Asahi's 2003 Super Hero Time block, alongside Bakuryū Sentai Abaranger.",
                'img' => "Kamen Rider/Era Heisei/4. Faiz/1.4 FaizRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Blade",
                'desc' => "Kamen Rider Blade (仮面ライダー剣［ブレイド］ Kamen Raidā Bureido, Masked Rider ♠ or Blade), is a Japanese tokusatsu drama and the 14th installment of the Kamen Rider Series. Debuting as the 5th entry of the Heisei Era, the show premiered on January 25, 2004 alongside Tokusou Sentai DekarangerIcon-crosswiki.png on TV Asahi's Super Hero Time block, and finished its 49-episode run on January 23, 2005.",
                'img' => "Kamen Rider/Era Heisei/5. Blade/1.5 BladeRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Hibiki",
                'desc' => "Kamen Rider Hibiki (仮面ライダー響鬼［ヒビキ］ Kamen Raidā Hibiki, Masked Rider Hibiki) is a Japanese tokusatsu superhero television series. It is the fifteenth installment in the popular Kamen Rider Series of tokusatsu programs. It is a joint collaboration between Ishimori Productions and Toei. Kamen Rider Hibiki first aired on January 30, 2005 and aired its final episode on January 22, 2006. It aired alongside Mahou Sentai MagirangerIcon-crosswiki.png for Super Hero Time 2005. This series is noted for introducing new themes and styles yet unseen in other shows. The catchphrase for the series is \"To us, there are heroes.\" (ぼくたちには、ヒーローがいる Bokutachi ni wa, hīrō ga iru).",
                'img' => "Kamen Rider/Era Heisei/6. Hibiki/1.6 HibikiRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Kabuto",
                'desc' => "Kamen Rider Kabuto (仮面ライダーカブト Kamen Raidā Kabuto, Masked Rider Kabuto) is a Japanese tokusatsu superhero television series. It is the sixteenth installment in the popular Kamen Rider Series of tokusatsu programs. It is a joint collaboration between Ishimori Productions and Toei. The series was broadcast on TV Asahi. The first episode aired on January 29, 2006, and with the final episode airing on January 21, 2007, completing the series with 49 episodes. It aired alongside GoGo Sentai BoukengerIcon-crosswiki.png for Super Hero Time 2006. The series represents the 35th anniversary of the Masked Rider Series, as indicated by a notice at the beginning of the pilot episode reading, in Japanese, \"Kamen Rider 35th Anniversary Production.\" Kamen Rider Kabuto is the first Kamen Rider Series to be broadcast in high-definition format.",
                'img' => "Kamen Rider/Era Heisei/7. Kabuto/1.7 KabutoRiders (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Den-O",
                'desc' => "Kamen Rider Den-O (仮面ライダー電王［デンオウ］ Kamen Raidā Den'ō, Masked Rider Den-O) is the seventeenth installment in the popular Kamen Rider Series of tokusatsu programs. It is a joint collaboration between Ishimori Productions and Toei. It premiered January 28, 2007 on TV Asahi, and concluded airing on January 20, 2008. It aired alongside Juken Sentai GekirangerIcon-crosswiki.png for Super Hero Time 2007. Its lead actor Takeru Satoh is the first Kamen Rider Series lead born in the Heisei period of Japanese history.",
                'img' => "Kamen Rider/Era Heisei/8. Den-O/1.8 Den-ORiders (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Kiva",
                'desc' => "Kamen Rider Kiva (仮面ライダーキバ Kamen Raidā Kiba, Masked Rider Kiva) is the title of the 2008 Kamen Rider Japanese tokusatsu television series produced by Toei Company and Ishimori Productions. It premiered on January 27, 2008, following the finale of Kamen Rider Den-O. It aired as a part of TV Asahi's 2008 Super Hero Time block with Engine Sentai Go-OngerIcon-crosswiki.png. Advertisements showed a horror film theme to the series, with the motif for Kamen Rider Kiva as a vampire. The advertising slogan for the series is \"Wake up! Break the chains of destiny!!\" (覚醒（ウェイクアップ）! 運命（さだめ）の鎖を解き放て!! Weiku appu! Sadame no kusari o tokihanate!!). The first episode began with a commemoration of the series in honor of the seventieth anniversary of Shotaro Ishinomori's birthday.",
                'img' => "Kamen Rider/Era Heisei/9. Kiva/1.9 KivaRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Decade",
                'desc' => "Kamen Rider Decade (仮面ライダーディケイド Kamen Raidā Dikeido, Masked Rider DCD, Masked Rider Decade) is a Japanese tokusatsu drama and the 19th entry of the Kamen Rider Series. The series is the 10th entry of the Heisei Era and commemorates all of the Rider series to date. It premiered on January 25, 2009 alongside Samurai Sentai ShinkengerIcon-crosswiki.png on TV Asahi's Super Hero Time block. After Kamen Rider Decade concluded early on August 30, 2009, Shinkenger was joined by Kamen Rider W.",
                'img' => "Kamen Rider/Era Heisei/10. Decade/1.10 DecadeRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "W",
                'desc' => "Kamen Rider Double (仮面ライダーＷ［ダブル］ Kamen Raidā Daburu) is the main and eponymous protagonist of Kamen Rider W, a Kamen Rider who transforms from two people, Shotaro Hidari and Philip.",
                'img' => "Kamen Rider/Era Heisei/11. W/2.1 WRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "OOO",
                'desc' => "Kamen Rider OOO (仮面ライダーＯＯＯ［オーズ］ Kamen Raidā Ōzu) is a 2010-2011 Japanese tokusatsu drama in Toei Company's Kamen Rider Series, being the twelfth series in the Heisei period run and the twenty-first overall. It began airing on September 5, 2010, the week following the conclusion of Kamen Rider W,[1] joining Tensou Sentai GoseigerIcon-crosswiki.png and then Kaizoku Sentai GokaigerIcon-crosswiki.png in the Super Hero Time lineup, until its conclusion on August 28, 2011. The series' titular Kamen Rider made a cameo appearance in the film Kamen Rider W Forever: A to Z/The Gaia Memories of Fate. The catchphrase for the series is \"I'll transform!!!\" (俺が変身する!!! Ore ga henshin suru!!!).",
                'img' => "Kamen Rider/Era Heisei/12. Ooo/2.2 OooRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Fourze",
                'desc' => "Kamen Rider Fourze (仮面ライダーフォーゼ Kamen Raidā Fōze) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series, being the thirteenth series in the Heisei period run and the twenty-second overall. It began airing on September 4, 2011, the week following the conclusion of Kamen Rider OOO, joining Kaizoku Sentai GokaigerIcon-crosswiki.png, later Tokumei Sentai Go-BustersIcon-crosswiki.png, in the Super Hero Time lineup. Trademarks on the title were filed by Toei in April 2011. The series commemorates not only the Kamen Rider Series' 40th anniversary but also the 50th anniversary of spaceflight, which began with Yuri Gagarin's Vostok 1 flight in 1961. The show's catchphrase is \"Switch on youth 'cause space is here!\" (青春スイッチオンで宇宙キター！ Seishun suitchi on de uchū kitā!), referencing the Fourze Driver transformation belt which gets its various powers from devices called Astroswitches to conjure attachments to Fourze's limbs. As with the two previous series, the protagonist of Fourze made his debut in the annual summer film of the show's direct predecessor, appearing in Kamen Rider OOO Wonderful: The Shogun and the 21 Core Medals.",
                'img' => "Kamen Rider/Era Heisei/13. Fourze/2.3 FourzeRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Wizard",
                'desc' => "Kamen Rider Wizard (仮面ライダーウィザード Kamen Raidā Uizādo) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series, being the fourteenth series in the Heisei period run and the twenty-third overall. Trademarks on the title were filed by Toei in June 21, 2012. It began airing on September 2, 2012, joining Tokumei Sentai Go-BustersIcon-crosswiki.png and then Zyuden Sentai KyoryugerIcon-crosswiki.png in the Super Hero Time line-up following the finale of Kamen Rider Fourze. With Wizard finished, Kamen Rider Gaim joined Kyoryuger as part of Super Hero Time. Tsuyoshi Kida is the series' main screenwriter.",
                'img' => "Kamen Rider/Era Heisei/14. Wizard/2.4 WizardRiders (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Gaim",
                'desc' => "Kamen Rider Gaim (仮面ライダー鎧武［ガイム］ Kamen Raidā Gaimu) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series, it is the fifteenth series in the Heisei period run and the twenty-fourth series overall. Toei registered the copyright and trademark of the series, which started on October 6, 2013, joining Zyuden Sentai KyoryugerIcon-crosswiki.png in the Super Hero Time line-up three weeks after the finale of Kamen Rider Wizard. After Kyoryuger concluded on February 9, 2014, Kamen Rider Gaim was joined in the Super Hero Time lineup with Ressha Sentai ToQgerIcon-crosswiki.png. After the finale of Kamen Rider Gaim, Kamen Rider Drive joined ToQger on the Super Hero Time block. The catchphrase for the series are \"It's a Rider Warring (Sengoku) era.\" (ライダー戦国時代。 Raidā Sengoku Jidai) and \"How would you use your power?\" (キミはこの力どう使う? Kimi wa kono chikara dō tsukau).",
                'img' => "Kamen Rider/Era Heisei/15. Gaim/2.5 GaimRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Drive",
                'desc' => "Kamen Rider Drive (仮面ライダードライブ Kamen Raidā Doraibu) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the sixteenth series in the Heisei period run and the twenty-fifth series overall. The series started on October 5, 2014, joining Ressha Sentai ToQgerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Gaim. Starting on February 22, 2015, Kamen Rider Drive was joined by Shuriken Sentai NinningerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Drive, Kamen Rider Ghost joined Ninninger in the Super Hero Time line-up. Its series tagline is \"Start Your Engine!\"",
                'img' => "Kamen Rider/Era Heisei/16. Drive/2.6 DriveRiders (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Ghost",
                'desc' => "Kamen Rider Ghost (仮面ライダーゴースト Kamen Raidā Gōsuto) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the seventeenth series in the Heisei period run and the twenty-sixth series overall. The series started on October 4, 2015, joining Shuriken Sentai NinningerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Drive. After Ninninger concluded on February 7, 2016, the series was joined by Doubutsu Sentai ZyuohgerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Ghost, Kamen Rider Ex-Aid joined Zyuohger in the Super Hero Time line-up.",
                'img' => "Kamen Rider/Era Heisei/17. Ghost/2.7 GhostRiders (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Ex-Aid",
                'desc' => "Kamen Rider Ex-Aid (仮面ライダーエグゼイド Kamen Raidā Eguzeido) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the eighteenth series in the Heisei period run and the twenty-seventh series overall. The series started on October 2, 2016, joining Doubutsu Sentai ZyuohgerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Ghost. Starting on February 12, 2017, the series was joined by Uchu Sentai KyurangerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Ex-Aid, Kamen Rider Build joined Kyuranger in the Super Hero Time line-up. In 2019, this became the first Kamen Rider to air in Indonesia on RTV since Kamen Rider OOO on Indosiar in 2014. This show currently airs on the North American Japanese-language channel TV Japan.",
                'img' => "Kamen Rider/Era Heisei/18. Ex-Aid/2.8 Ex-AidRiders (3).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Build",
                'desc' => "Kamen Rider Build (仮面ライダービルド Kamen Raidā Birudo) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the nineteenth and penultimate series for a full Heisei period run and the twenty-eighth series overall. The series started on September 3, 2017, joining Uchu Sentai KyurangerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Ex-Aid. After Kyuranger concluded on February 4, 2018, the series was joined by Kaitou Sentai Lupinranger VS Keisatsu Sentai PatrangerIcon-crosswiki.png in the Super Hero Time line-up. After the finale of Kamen Rider Build, Kamen Rider Zi-O joined Lupinranger VS Patranger on the Super Hero Time block.",
                'img' => "Kamen Rider/Era Heisei/19. Build/2.9 BuildRiders (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $kamenrider,
                'name' => "Zi-O",
                'desc' => "Kamen Rider Zi-O (仮面ライダージオウ Kamen Raidā Jiō) is a Japanese tokusatsu drama in Toei Company's Kamen Rider Series. It is the twentieth and final series in the Heisei period run, the first series to be produced around the Reiwa period, and the twenty-ninth series overall. The series started on September 2, 2018, joining Kaitou Sentai Lupinranger VS Keisatsu Sentai PatrangerIcon-crosswiki.png in the Super Hero Time line-up after the finale of Kamen Rider Build. After Lupinranger VS Patranger’s conclusion, it was joined by 4 Week Continuous Special Super Sentai Strongest Battle!!Icon-crosswiki.png in February 2019 and later Kishiryu Sentai RyusoulgerIcon-crosswiki.png in March 2019. After the finale of Kamen Rider Zi-O, Ryusoulger would air alongside Kamen Rider Zero-One in the Super Hero Time block.",
                'img' => "Kamen Rider/Era Heisei/20. Zi-O/2.10 Zi-ORiders (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Zero-One',
                'desc' => null,
                'img' => "Kamen Rider/Era Reiwa/1. Zero-One/Zero-One (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Saber',
                'desc' => null,
                'img' => "Kamen Rider/Era Reiwa/2. Saber/Saber (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Revice',
                'desc' => null,
                'img' => "Kamen Rider/Era Reiwa/3. Revice/Revice (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Geats',
                'desc' => null,
                'img' => "Kamen Rider/Era Reiwa/4. Geats/Geats (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $kamenrider,
                'name' => 'Gotchard',
                'desc' => null,
                'img' => "Kamen Rider/Era Reiwa/5. Gotchard/Gotchard (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Gorenger',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/1. Himitsu Sentai Goranger Five Rangers (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'J.A.K.Q.',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/2. J.A.K.Q. Dengekitai JAKQ (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Fever J',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/3. Battle Fever J (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Denziman',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/4. Denshi Sentai Denjiman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Sun Vulcan',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/5. Taiyo Sentai Sun Vulcan (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Goggle V',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/6. Dai Sentai Goggle Five (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Dynaman',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/7. Kagaku Sentai Dynaman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Bioman',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/8. Choudenshi Bioman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Changeman',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/9. Dengeki Sentai Changeman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Flashman',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/10. Choushinsei Flashman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Maskman',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/11. Hikari Sentai Maskman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $supersentai,
                'name' => 'Liveman',
                'desc' => null,
                'img' => "Super Sentai/Era Showa/12. Choujuu Sentai Liveman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Turboranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/13. Kousoku Sentai Turboranger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Fiveman',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/14. Chikyuu Sentai Fiveman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Jetman',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/15. Choujin Sentai Jetman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Zyuranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/16. Kyouryuu Sentai Zyuranger (JPN) - Mighty Morphin Power Rangers (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Dairanger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/17. Gosei Sentai Dairanger (JPN) - Mighty Morphin Power Rangers 2 (USA) - Star Ranger (INA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Kakuranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/18. Ninja Sentai Kakuranger (JPN) - Mighty Morphin Power Alien Rangers 3 (USA) - Ninja Ranger (INA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Ohranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/19. Choriki Sentai Ohranger (JPN) - Power Rangers Zeo (USA) - Oh Ranger (INA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Carranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/20. Gekisou Sentai Carranger (JPN) - Power Rangers Turbo (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Megaranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/21. Denji Sentai Megaranger (JPN) - Power Rangers In Space (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gingaman',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/22. Seijuu Sentai Gingaman (JPN) - Power Rangers Lost Galaxy (USA) (6).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Go Go V',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/23. KyuKyu Sentai GoGo V (JPN) - Power Rangers Lightspeed Rescue(USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Timeranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/24. Mirai Sentai Timeranger (JPN) - Power Rangers Time Force (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gaoranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/25. Hyaku Juu Sentai Gaoranger (JPN) - Power Rangers Wild Force (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Hurricaneger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/26. Ninpuu Sentai Hurricanger (JPN) - Power Rangers Ninja Storm (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Abaranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/27. BakuRyuu Sentai Abaranger (JPN) - Power Rangers Dino Thunder (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Dekaranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/28. Tokusou Sentai Dekaranger (JPN) - Power Rangers S.P.D (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Magiranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/29. Mahou Sentai Magiranger (JPN) - Power Rangers Mystic Force (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Boukenger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/30. Gougou Sentai Boukenger (JPN) - Power Rangers Operation Overdrive (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gekiranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/31. Juken Sentai Gekiranger (JPN) - Power Rangers Jungle Fury (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Go-onger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/32. Engine Sentai Go-Onger (JPN) - Power Rangers RPM (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Shinkenger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/33. Samurai Sentai Shinkenger (JPN) - Power Rangers Samurai (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Goseiger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/34. Tensou Sentai Goseiger (JPN) - Power Rangers Megaforce (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Gokaiger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/35. Kaizoku Sentai Gokaiger (JPN) - Power Rangers Super Megaforce (USA) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Go-Busters',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/36. Tokumei Sentai Go-Busters  (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Kyoryuger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/37. Zyuden Sentai Kyoryuger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'ToQger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/38. Ressha Sentai Tokkyuger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Ninninger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/39. Shuriken Sentai Ninninger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Zyuohger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/40. Doubutsu Sentai Zyouhger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Kyuuranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/41. Uchuu Sentai Kyuuranger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Lupinranger VS Patranger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/42. Kaitou Sentai Lupinranger _ Keisatsu Sentai Patranger (Lupat Rangers) (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $supersentai,
                'name' => 'Ryusoulger',
                'desc' => null,
                'img' => "Super Sentai/Era Heisei/43. Kishiryu Sentai Ryusoulger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Kiramager',
                'desc' => null,
                'img' => "Super Sentai/Era Reiwa/1. Mashin Sentai Kiramager/Mashin Sentai Kiramager (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Zenkaiger',
                'desc' => null,
                'img' => "Super Sentai/Era Reiwa/2. Kikai Sentai Zenkaiger/Kikai Sentai Zenkaiger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Donbrothers',
                'desc' => null,
                'img' => "Super Sentai/Era Reiwa/3. Avataro Sentai Donbrothers/Avataro Sentai Donbrothers (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'King-Ohger',
                'desc' => null,
                'img' => "Super Sentai/Era Reiwa/4. Ohsama Sentai King-Ohger/Ohsama Sentai King-Ohger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $supersentai,
                'name' => 'Boonboomger',
                'desc' => null,
                'img' => "logo.png",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Ultraman',
                'desc' => null,
                'img' => "Ultraman/Era Showa/1. Ultraman/Ultraman (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Ultra Seven',
                'desc' => null,
                'img' => "Ultraman/Era Showa/2. Ultra Seven/Ultra Seven (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Jack',
                'desc' => null,
                'img' => "Ultraman/Era Showa/3. Ultraman Jack/Ultraman Jack (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Ace',
                'desc' => null,
                'img' => "Ultraman/Era Showa/4. Ultraman Ace/Ultraman Ace (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Taro',
                'desc' => null,
                'img' => "Ultraman/Era Showa/5. Ultraman Taro/Ultraman Taro (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Leo',
                'desc' => null,
                'img' => "Ultraman/Era Showa/6. Ultraman Leo/Ultraman Leo (2).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => '80',
                'desc' => null,
                'img' => "Ultraman/Era Showa/7. Ultraman 80/Ultraman 80 (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $showa,
                'franchise_id' => $ultraman,
                'name' => 'Zoffy',
                'desc' => null,
                'img' => "Ultraman/Era Showa/8. Ultraman Zoffy/Ultraman Zoffy (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Tiga',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/1. Ultraman Tiga/Ultraman Tiga (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Dyna',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/2. Ultraman Dyna/Ultraman Dyna (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Gaia',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/3. Ultraman Gaia/Ultraman Gaia (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Cosmos',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/4. Ultraman Cosmos/Ultraman Cosmos (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Nexus',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/5. Ultraman Nexus/Ultraman Nexus (3).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Max',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/6. Ultraman Max/Ultraman Max (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Zero',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/7. Ultraman Zero/Ultraman Zero (3).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Ginga',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/8. Ultraman Ginga/Ultraman Ginga (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Ginga S',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/9. Ultraman Ginga S/Ultraman Ginga S (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'X',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/10. Ultraman X/Ultraman X (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Orb',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/11. Ultraman Orb/Ultraman Orb (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'Geed',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/12. Ultraman Geed/Ultraman Geed (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $heisei,
                'franchise_id' => $ultraman,
                'name' => 'R/B',
                'desc' => null,
                'img' => "Ultraman/Era Heisei/13. Ultraman RB/Ultraman RB (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Taiga',
                'desc' => null,
                'img' => "Ultraman/Era Reiwa/1. Ultraman Taiga/Ultraman Taiga (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Z',
                'desc' => null,
                'img' => "Ultraman/Era Reiwa/2. Ultraman Z/Ultraman Z (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Trigger',
                'desc' => null,
                'img' => "Ultraman/Era Reiwa/3. Ultraman Trigger/Ultraman Trigger (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Decker',
                'desc' => null,
                'img' => "Ultraman/Era Reiwa/4. Ultraman Decker/Ultraman Decker (1).jpg",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => Str::uuid(),
                'era_id' => $reiwa,
                'franchise_id' => $ultraman,
                'name' => 'Blazar',
                'desc' => null,
                'img' => "logo.png",
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ];
        Category::query()->insert($categories);
    }

    private function Era(string $name): string
    {
        $era = Era::where('name', $name)->first();
        if (!$era) {
            $era = Era::create([
                'id' => Str::uuid(),
                'name' => $name,
            ]);
        }
        return $era->id;
    }

    private function Franchise(string $name): string
    {
        $franchise = Franchise::where('name', $name)->first();
        if (!$franchise) {
            $franchise = Franchise::create([
                'id' => Str::uuid(),
                'name' => $name,
            ]);
        }
        return $franchise->id;
    }
}
